version: '3' 

services:
  app:
    container_name: react-web-app
    image: node:17-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm install && npm run start_docker"
    ports:
      - '3000:3000'